### ISSUE TITLE
Optifine wont download for 1.16.5

### ISSUE THREAD

**Issue by Csquaredaap** [ImpactDevelopment/Installer#122] opened 2021-02-12 00:16 UTC
I have the 1.16.5 nightly version and when i click include optifine it says null and I cant get optifine with the impact client

**Comment by notahumanthatisimportant** [comment] 2021-03-14 04:50
You have to download it from optifine and in the installer specify the file path to optifine

**Comment by Dysproh** [comment] 2021-04-01 02:44
The path can't be manually specified on 1.16.5.

**Comment by LeafHacker** [comment] 2021-06-20 19:21
Duplicate of #126

**Closed by LeafHacker** 2021-06-20 19:21 UTC
Labels: bug
