### ISSUE TITLE
travis is fucked

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/Installer#66] opened 2019-08-17 22:13 UTC

**Comment by LastedGuide** [comment] 2019-08-18 13:20
wth why did this happen, i cant make pull requests

**Comment by LeafHacker** [comment] 2019-09-17 19:15
the optimize task is throwing NPEs for me locally, I assume travis is having the same problem

**Comment by LeafHacker** [comment] 2019-09-21 16:14
Duplicate of #68

**Closed by LeafHacker** 2019-09-21 16:14 UTC
Labels: bug

**Comment by 0-x-2-2** [comment] 2019-09-22 18:32
crying and shaking the other pr is the duplicate this one was first.

**Comment by LeafHacker** [comment] 2019-09-22 18:35
the other issue is more specific to the root cause.
